### ISSUE TITLE
ERROR: Could not build wheels for llama_cpp_python, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by ice-xz** [BaranziniLab/KG_RAG#32]
How to solve it？
![截图](https://github.com/BaranziniLab/KG_RAG/assets/102570605/42ab9a98-4f79-4ae2-b64c-bc6951366393)

**Comment by karthiksoman** [comment]
This appears to be a new issue which I haven't encountered before. However, I found another github issue in the oobabooga repo that addresses this (link is given below). This issue is closed in that repo, which means that should have probably resolved. I hope this would bring a solution to your issue!
https://github.com/oobabooga/text-generation-webui/issues/1534
